# Generated by Django 4.2.2 on 2023-08-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcomida',
            name='permiso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localcomida',
            name='ventas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='localrepuesto',
            name='permiso',
            field=models.FloatField(),
        ),
    ]
