# Generated by Django 4.2.2 on 2023-08-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecapp', '0002_alter_localcomida_permiso_alter_localcomida_ventas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localrepuesto',
            name='permiso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
